version: '3.9'

services:
  eav-db:
    image: postgis/postgis:latest
    container_name: eav-db
    environment:
      POSTGRES_DB: eav
      POSTGRES_USER: eav_user
      POSTGRES_PASSWORD: eav_pass
    ports:
      - "5432:5432"
    networks:
      - eav-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "eav_user", "-d", "eav"]
      interval: 10s
      timeout: 5s
      retries: 5

  eav-backend:
    image: ghcr.io/openearthplatforminitiative/entity-attribute-backend:latest
    container_name: eav-backend
    depends_on:
      eav-db:
        condition: service_healthy
    environment:
      IMPORT_ENTITIES: false
      UPDATE_ENTITIES: false
      IMPORT_CONFIG: "examples/entities"
      ENABLE_ASSETS: false
      ENABLE_ADMIN_API: true
      ENABLE_METRICS: false
      POSTGRES_USER: eav_user
      POSTGRES_PASSWORD: eav_pass
      POSTGRES_DB: eav
      POSTGRES_HOST: eav-db
      LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    networks:
      - eav-net

networks:
  eav-net:
    driver: bridge
